# Generated by Django 3.0.2 on 2020-01-27 22:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200127_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 22, 29, 13, 987907, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 22, 29, 13, 987350, tzinfo=utc)),
        ),
    ]
